eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  cloud:
    config:
      uri: http://localhost:8888
      profile: default
      fail-fast: true
