eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: false
      fetch-registry: false
    instance:
      prefer-ip-address: true

#spring:
#  cloud:
#    config:
#      uri: http://localhost:8888
#      fast
