eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: localhost

spring:
  cloud:
    config:
      fail-fast: true
  retry:
    max-attempts: 5
    multiplier: 1.5
    initial-interval: 1000